[project]
name = "pytch-demos"
version = "0.1.0"
description = "Collection of demos for Pytch"
authors = [
    {name = "Ben North",email = "ben.north@tcd.ie"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black (>=25.11.0,<26.0.0)",
    "click (>=8.3.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
package-mode = false
